name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
assignees:
  - tigattack
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: project_version
    attributes:
      label: VeeamNotify version
      description: This can be found in the footer of any notification or in `C:\VeeamScripts\VeeamNotify\resources\version.txt`.
      options:
        - '1.0-beta1'
    validations:
      required: true
  - type: input
    id: veeam_version
    attributes:
      label: Veeam Backup & Replication build number
      description: This can be found Veeam B&R console (Menu > Help > About > Build).
      placeholder: e.g. 11.0.1.1261
    validations:
      required: false
  - type: dropdown
    id: pwsh_version
    attributes:
      label: PowerShell version
      description: This can be found by running `$PSVersionTable` in PowerShell.
      options:
        - '3.0'
        - '4.0'
        - '5.0'
        - '5.1'
        - '6.x'
        - '7.x'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, AFTER removing any sensitive information such as webhooks or user information. Logging can be enabled in `C:\VeeamScripts\VeeamNotify\config\conf.json` and logs can be found in `C:\VeeamScripts\VeeamNotify\logs\`.
      render: PowerShell
