name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] "
labels: ["enhancement"]
assignees:
  - tigattack
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us out!
  - type: textarea
    id: is-problem
    attributes:
      label: Is your feature request related to a problem?
      description: If so, please describe it
      placeholder: Tell us what bugs you!
  - type: textarea
    id: suggestion
    attributes:
      label: Describe your ideal solution
      description: How would you like to see this feature implemented?
      placeholder: |
        Definition of done: _A short, concise definition of how this feature would look or work when done._
        Stretch: _Any additional functionality that isn't required but would be nice._
      value: |
        Definition of done:
    validations:
      required: true
