---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: ./.github/scripts/Install-PSSA.ps1

    - name: Run PSScriptAnalyzer
      shell: pwsh
      run: ./.github/scripts/Run-PSSA.ps1
