name: Publish Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download build workflow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: Extract version from tag
        id: get_tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\/version\//, '');

      - name: Create release asset
        run: |
          shopt -s extglob
          name="VeeamNotify-${{ steps.tag.outputs.result }}"
          mkdir "$name"
          cp -rv !($name) $name/
          zip -r "$name.zip" "./$name" -x "./$name/.*/*" "./$name/.*" "./$name/*/.gitkeep" "./$name/asset/*" "./$name/tests/*" "./$name/README.md"
          rm -r "$name"

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: VeeamNotify-${{ steps.tag.outputs.result }}.zip
          name: "Release ${{ steps.tag.outputs.result }}"
