---
name: PSScriptAnalyzer

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed PowerShell files
        id: changed-files
        uses: tj-actions/changed-files@v18
        with:
          files: |
            **/*.ps1
            **/*.psm1
            **/*.psd1
            !tests/*

      - name: List changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Update PSScriptAnalyzer
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: pwsh
        run: |
          $module = Get-Module -Name PSScriptAnalyzer
          $module | Remove-Module -Force
          $module | Update-Module -Force
          Import-Module -Name PSScriptAnalyzer -Force

      - name: Run PSScriptAnalyzer
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: pwsh
        run: |
          $changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}".Split(' ')
          ./.github/scripts/Run-PSSA.ps1 -Files $changedFiles
